feat: choice slider
helsenorge/refero pull request #142
Opened 2023-12-15 09:06 UTC by alibo42

2023-12-15 09:34 UTC, FreddyNO requested changes

2023-12-15 09:34 UTC, FreddyNO commented on src/components/__tests__/onChange-spec.tsx
> +import { act } from 'react-dom/test-utils';
Blir act brukt her?

2023-12-19 09:27 UTC, FreddyNO approved these changes

2023-12-19 14:58 UTC, AG-83 approved these changes

2023-12-20 14:03 UTC, merged